### ISSUE TITLE
[Oculus Quest2]  About using unreal libretro in Oculus Quest 2.

### ISSUE THREAD

**Issue by yosanyu** [N7Alpha/UnrealLibretro#14]
Hello, I want to ask about using unreal libretro in Oculus Quest 2.
I used LibretroTVActor to run rom game.
When destroy the object(LibretroTVActor), during 1~2 minutes, application will crash in Quest 2.
How can I solve this problem?
Version is 4.27.

**Comment by N7Alpha** [comment]
Do you have a crash log? It should look like the thing I posted in #12.  I think it shows up in the device output window if you're running in the Unreal Editor. I'll try looking at this tomorrow night and see if I can reproduce it.

Also what core and rom were you using?

**Comment by yosanyu** [comment]
`LogPlayLevel: ********** RUN COMMAND STARTED **********
LogPlayLevel: Starting Client....
LogPlayLevel: Completed Launch On Stage: Deploy Task, Time: 91.937616
LogPlayLevel: Took 0.1617632s to run adb.exe, ExitCode=0
LogPlayLevel: GetPackageInfo ReturnValue: com.YourCompany.MyProject
LogPlayLevel:   --------- beginning of system
LogPlayLevel:   --------- beginning of tracking
LogPlayLevel:   --------- beginning of main
LogPlayLevel: Error:   03-25 13:00:29.063 25098 25215 D UE4     : [2022.03.25-05.00.29:063][  9]LogHMD: Error: FOculusHMDModule::GetPluginWrapper().BeginFrame4 1 failed (-1003)
LogPlayLevel: Error:   03-25 13:00:29.090 25098 25215 D UE4     : [2022.03.25-05.00.29:090][ 11]LogHMD: Error: FOculusHMDModule::GetPluginWrapper().BeginFrame4 2 failed (-1003)
LogPlayLevel: Error:   03-25 13:00:29.097 25098 25215 D UE4     : [2022.03.25-05.00.29:097][ 11]LogHMD: Error: FOculusHMDModule::GetPluginWrapper().BeginFrame4 3 failed (-1003)
LogPlayLevel: Error:   03-25 13:00:29.116 25098 25215 D UE4     : [2022.03.25-05.00.29:116][ 13]LogHMD: Error: FOculusHMDModule::GetPluginWrapper().BeginFrame4 4 failed (-1003)
LogPlayLevel: Error:   03-25 13:00:29.136 25098 25215 D UE4     : [2022.03.25-05.00.29:136][ 14]LogHMD: Error: FOculusHMDModule::GetPluginWrapper().BeginFrame4 5 failed (-1003)
LogPlayLevel: Error:   03-25 13:00:29.146 25098 25215 D UE4     : [2022.03.25-05.00.29:146][ 14]LogHMD: Error: FOculusHMDModule::GetPluginWrapper().BeginFrame4 6 failed (-1003)
LogPlayLevel: Error:   03-25 13:00:29.163 25098 25215 D UE4     : [2022.03.25-05.00.29:163][ 15]LogHMD: Error: FOculusHMDModule::GetPluginWrapper().BeginFrame4 7 failed (-1003)
LogPlayLevel: Error:   03-25 13:00:29.179 25098 25215 D UE4     : [2022.03.25-05.00.29:179][ 16]LogHMD: Error: FOculusHMDModule::GetPluginWrapper().BeginFrame4 8 failed (-1003)
LogPlayLevel: Error:   03-25 13:00:29.196 25098 25215 D UE4     : [2022.03.25-05.00.29:196][ 17]LogHMD: Error: FOculusHMDModule::GetPluginWrapper().BeginFrame4 9 failed (-1003)
LogPlayLevel: Error:   03-25 13:00:29.212 25098 25215 D UE4     : [2022.03.25-05.00.29:212][ 18]LogHMD: Error: FOculusHMDModule::GetPluginWrapper().BeginFrame4 10 failed (-1003)
LogPlayLevel: Error:   03-25 13:00:29.229 25098 25215 D UE4     : [2022.03.25-05.00.29:229][ 19]LogHMD: Error: FOculusHMDModule::GetPluginWrapper().BeginFrame4 11 failed (-1003)
LogPlayLevel:   03-25 13:00:29.895 25098 25136 D UE4     : EngineMemoryWarningHandler: Mem Used 354.40 MB, Texture Memory 19.51 MB, Render Target memory 162.70 MB, OS Free 3015.20 MB
LogPlayLevel:   03-25 13:00:30.022 25098 25138 D UE4     : [GameActivity] Used memory: 478764 (VmRSS:   362972 kB)
LogPlayLevel:   03-25 13:00:39.191 25098 25576 V UE4     : [NetworkChangedManager] Connectivity hasn't changed. Current state: CONNECTION_AVAILABLE
LogPlayLevel:   03-25 13:00:39.191 25098 25576 V UE4     : [NetworkChangedManager] Full network check complete. State: CONNECTION_AVAILABLE
LogPlayLevel:   03-25 13:00:40.267 25098 25138 D UE4     : [GameActivity] Used memory: 478077 (VmRSS:   365096 kB)
LogPlayLevel:   03-25 13:00:41.977 25098 25119 V UE4     : [NetworkChangedManager] Network Capabilities changed, has Internet: true
LogPlayLevel:   03-25 13:00:41.978 25098 25583 V UE4     : [NetworkChangedManager] Verifying internet connection with host: https://example.com/
LogPlayLevel:   03-25 13:00:42.123 25098 25583 V UE4     : [NetworkChangedManager] Connectivity hasn't changed. Current state: CONNECTION_AVAILABLE
LogPlayLevel:   03-25 13:00:42.123 25098 25583 V UE4     : [NetworkChangedManager] Full network check complete. State: CONNECTION_AVAILABLE
LogPlayLevel:   03-25 13:00:50.544 25098 25138 D UE4     : [GameActivity] Used memory: 478469 (VmRSS:   365440 kB)
LogPlayLevel:   03-25 13:00:53.802 25098 25098 D UE4     : [GameActivity] Battery: status = 4, rawlevel = 100, scale = 100
LogPlayLevel:   03-25 13:00:53.802 25098 25098 D UE4     : nativeBatteryEvent(stat = 4, lvl = 100  temp = 32.20 °C)
LogPlayLevel:   03-25 13:00:54.065 25098 25119 V UE4     : [NetworkChangedManager] Network Capabilities changed, has Internet: true
LogPlayLevel:   03-25 13:00:54.067 25098 25611 V UE4     : [NetworkChangedManager] Verifying internet connection with host: https://example.com/
LogPlayLevel:   03-25 13:00:54.231 25098 25611 V UE4     : [NetworkChangedManager] Connectivity hasn't changed. Current state: CONNECTION_AVAILABLE
LogPlayLevel:   03-25 13:00:54.231 25098 25611 V UE4     : [NetworkChangedManager] Full network check complete. State: CONNECTION_AVAILABLE
LogPlayLevel:   03-25 13:01:00.812 25098 25138 D UE4     : [GameActivity] Used memory: 477993 (VmRSS:   365192 kB)
LogPlayLevel:   03-25 13:01:03.103 25098 25119 V UE4     : [NetworkChangedManager] Network Capabilities changed, has Internet: true
LogPlayLevel:   03-25 13:01:03.104 25098 25672 V UE4     : [NetworkChangedManager] Verifying internet connection with host: https://example.com/
LogPlayLevel:   03-25 13:01:03.337 25098 25672 V UE4     : [NetworkChangedManager] Connectivity hasn't changed. Current state: CONNECTION_AVAILABLE
LogPlayLevel:   03-25 13:01:03.337 25098 25672 V UE4     : [NetworkChangedManager] Full network check complete. State: CONNECTION_AVAILABLE
LogPlayLevel:   03-25 13:01:09.126 25098 25119 V UE4     : [NetworkChangedManager] Network Capabilities changed, has Internet: true
LogPlayLevel:   03-25 13:01:09.129 25098 25685 V UE4     : [NetworkChangedManager] Verifying internet connection with host: https://example.com/
LogPlayLevel:   03-25 13:01:09.281 25098 25685 V UE4     : [NetworkChangedManager] Connectivity hasn't changed. Current state: CONNECTION_AVAILABLE
LogPlayLevel:   03-25 13:01:09.281 25098 25685 V UE4     : [NetworkChangedManager] Full network check complete. State: CONNECTION_AVAILABLE
LogPlayLevel:   03-25 13:01:11.060 25098 25138 D UE4     : [GameActivity] Used memory: 479085 (VmRSS:   366032 kB)
LogPlayLevel:   03-25 13:01:15.149 25098 25119 V UE4     : [NetworkChangedManager] Network Capabilities changed, has Internet: true
LogPlayLevel:   03-25 13:01:15.152 25098 25726 V UE4     : [NetworkChangedManager] Verifying internet connection with host: https://example.com/
LogPlayLevel:   03-25 13:01:15.319 25098 25726 V UE4     : [NetworkChangedManager] Connectivity hasn't changed. Current state: CONNECTION_AVAILABLE
LogPlayLevel:   03-25 13:01:15.319 25098 25726 V UE4     : [NetworkChangedManager] Full network check complete. State: CONNECTION_AVAILABLE
LogPlayLevel:   03-25 13:01:18.176 25098 25119 V UE4     : [NetworkChangedManager] Network Capabilities changed, has Internet: true
LogPlayLevel:   03-25 13:01:18.177 25098 25734 V UE4     : [NetworkChangedManager] Verifying internet connection with host: https://example.com/
LogPlayLevel:   03-25 13:01:18.321 25098 25734 V UE4     : [NetworkChangedManager] Connectivity hasn't changed. Current state: CONNECTION_AVAILABLE
LogPlayLevel:   03-25 13:01:18.321 25098 25734 V UE4     : [NetworkChangedManager] Full network check complete. State: CONNECTION_AVAILABLE
LogPlayLevel:   03-25 13:01:21.338 25098 25138 D UE4     : [GameActivity] Used memory: 478810 (VmRSS:   365796 kB)
LogPlayLevel:   03-25 13:01:26.427 25098 25098 D UE4     : [GameActivity] Battery: status = 4, rawlevel = 100, scale = 100
LogPlayLevel:   03-25 13:01:26.427 25098 25098 D UE4     : nativeBatteryEvent(stat = 4, lvl = 100  temp = 32.50 °C)
LogPlayLevel:   03-25 13:01:30.032 25098 25536 D UE4     : [2022.03.25-05.01.30:032][667]LogRHI: TextureReferenceRevertsLastRenderContainer, no config rule set: 1
LogPlayLevel:   03-25 13:01:31.379 25098 25119 V UE4     : [NetworkChangedManager] Network Capabilities changed, has Internet: true
LogPlayLevel:   03-25 13:01:31.381 25098 25763 V UE4     : [NetworkChangedManager] Verifying internet connection with host: https://example.com/
LogPlayLevel:   --------- beginning of crash
LogPlayLevel:   03-25 13:01:31.532 25098 25763 V UE4     : [NetworkChangedManager] Connectivity hasn't changed. Current state: CONNECTION_AVAILABLE
LogPlayLevel:   03-25 13:01:31.532 25098 25763 V UE4     : [NetworkChangedManager] Full network check complete. State: CONNECTION_AVAILABLE
LogPlayLevel:   03-25 13:01:31.830 25098 25138 D UE4     : [GameActivity] Used memory: 417714 (VmRSS:   351112 kB)
LogPlayLevel: Took 1.4159037s to run adb.exe, ExitCode=0
LogPlayLevel: Took 0.4696716s to run adb.exe, ExitCode=0
LogPlayLevel: ********** RUN COMMAND COMPLETED **********
LogPlayLevel: BUILD SUCCESSFUL
LogPlayLevel: Completed Launch On Stage: Run Task, Time: 84.939668
LogPlayLevel: Completed Launch On Stage: Post Launch Task, Time: 0.000008
LogPlayLevel: AutomationTool exiting with ExitCode=0 (Success)
LogPlayLevel: Launch On Completed. Time: 220.736759`

I tried cores(armv8) include nestopia, gearboy, snes9x, mupen64plus_next_gles3, vbam, desmume2015 and mame2003.
The crash logs is from vbam.
I saw crash logs of desmume2015 is similar.
Every core will let application crash when destroing LibretroTVActor.
Thanks for your reply.

**Comment by N7Alpha** [comment]
Thanks for posting the log. I think the issue coincidently was fixed in 4f42d23. I made a [new release]() but you should be able to just pull the new source code with `git`  if you have that or just download the source and overwrite it too. If everything works you can close the issue otherwise let me know if somethings still wrong.

Sorry I got back to you a little late I was playing Elden Ring.
