### ISSUE TITLE
Minor issue - relative path in PIE when using DOSBOX (UE5)

### ISSUE THREAD

**Issue by masterkyodai** [N7Alpha/UnrealLibretro#16]
When I use DOSBOX in UE5 it works fine, but in PIE the relative path is kinda broken. Like when I do "mount c .\" the home dir (".\") points to C:\Program Files\Epic Games\UE_5.0\Engine\Binaries\Win64\ instead of the project plugin ROMS folder. It did work correctly in UE4 so prolly some problem with either UE5 or the dosbox_svn_libretro.dll. Just wanted to mention it anyways.

Edit: github removes the backslashes here for "dot backslash", but i guess we still all understand what i wanna say here.

**Comment by N7Alpha** [comment]
Thanks! I'll look into this

**Comment by N7Alpha** [comment]
It looks like you might have found a bug in that core. I made a [pull request](https://github.com/libretro/dosbox-svn/pull/81) so they'll probably fix it on their end. If not it can be fixed by using the windows path separator `\` when calling `retro_load_game`.

**Comment by N7Alpha** [comment]
... Turns out that `dosbox-svn` is basically deprecated at this point. I would just use the other cores if they work
