### ISSUE TITLE
Please allow RETRO_DEVICE_NONE in the "Libretro Core Controllers" category of the editor

### ISSUE THREAD

**Issue by AltoRetrato** [N7Alpha/UnrealLibretro#26]
Currently, at least with the Flycast (Dreamcast) core, all ports of the console have the `RETRO_DEVICE_DEFAULT` controller, and it is not possible (AFAIK) to set a port to `RETRO_DEVICE_NONE`.

![image](https://github.com/N7Alpha/UnrealLibretro/assets/22997468/5f4aeef8-2998-45ac-b9f9-4339fe61ed7f)

**Comment by N7Alpha** [comment]
This was an oversight. I'll fix it soon. I think Retroarch defaults to `RETRO_DEVICE_JOYPAD` with the option to change it to `RETRO_DEVICE_JOYPAD` so I'll do the same
