### ISSUE TITLE
Discord invite invalid

### ISSUE THREAD

**Issue by azukaar** [N7Alpha/UnrealLibretro#6]
Just wanted to share a demo I did today to try out the library!

https://www.youtube.com/watch?v=tbtL4HMy_Ak

https://www.youtube.com/watch?v=kIjplDznyRE

Enjoy

**Comment by N7Alpha** [comment]
I updated the link so it should be working now hopefully. Sorry about that.

That demo looks pretty cool. Good job on getting it working so quickly I know the documentation is a bit sparse. Let me know if you hit any other snags.

**Comment by azukaar** [comment]
Great --
Let me know how you prefer to proceed for issues and stuff, do you want me to use the Discord's #Support or Tickets in GH ? Latter probably preferable but up to you
