### ISSUE TITLE
Just can't get PUAE working

### ISSUE THREAD

**Issue by masterkyodai** [N7Alpha/UnrealLibretro#9]
Just can't get PUAE working. I tried several versions but they all crash. I think they rely on some stuff that isn't implemented yet.

[2021.10.23-22.08.06:639][423]Libretro: Warning: Unhandled env #65572
[2021.10.23-22.08.06:776][437]Libretro: 6888x no FPU: f201 00009000 PC=00f80ca0

[2021.10.23-22.08.06:776][437]Libretro: B-Trap f201 at f80ca0 (000001d782714450)

**Comment by masterkyodai** [comment]
Closed - was actually missing the soundfiles for Floppy sounds.

**Comment by N7Alpha** [comment]
I tried messing with this and found it segfaulted trying to call an led callback function I didn't implement when trying to run Monkey Island 2. So I pushed a commit to fix that. Not sure if you ever ran into the same issue.

Also I saw you were working on config support. If you get that working don't hesitate to make a pull request I can probably fix the conflicts too depending on how familiar you are with git.

**Comment by masterkyodai** [comment]
Ah haven't tried MI2 yet. Thanks a lot for fixing the LED callback.

I struggled a lot with C++ - not my language i must admit. My idea was to just dump the default core config into a text file instead of a table and read it out if it already exists. But yeah I wasn't even able to create a simple text file in C++... The types in C++ drive me crazy.
